# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: crypto-ixian
app: crypto-ixian-bot

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, env:STAGE, "dev"}
  region: ca-central-1
  environment:
    ENV: ${opt:stage, env:STAGE, "dev"}
    KUCOIN_URL_ALLTICKERS: https://api.kucoin.com/api/v1/market/allTickers
    SANTIMENT_KEY: ${env:SANTIMENT_KEY}
    TABLE_DISCOVERY: ${self:custom.tableDiscovery}
    TABLE_HARVEST: ${self:custom.tableHarvest}
    TABLE_STRATEGY_META: ${self:custom.tableStrategyMeta}
    TABLE_STRATEGY_DETAILS: ${self:custom.tableStrategyDetails}
    QUEUE_HARVEST: ${self:custom.queueHarvest}
    QUEUE_STRATEGY: ${self:custom.queueStrategy}
    SNS_TOPIC_DISCOVERY: ${self:custom.snsTopicDiscovery}
    SNS_TOPIC_STRATEGY: ${self:custom.snsTopicStrategy}
    SES_SENDER: ${self:custom.sesSender}
    SES_RECIPIENT: ${self:custom.sesRecipient}
    STRATEGY_DAA_ENTER : ${self:custom.strategyDAAEnter}
    STRATEGY_DAA_EXIT : ${self:custom.strategyDAAExit}
    STRATEGY_SMA_LOOKBACK : ${self:custom.strategySMALookback}
    STRATEGY_VOLATILITY_ENTER : ${self:custom.strategyVolatilityEnter}
    STRATEGY_VOLATILITY_EXIT : ${self:custom.strategyVolatilityExit}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:SendMessageBatch
        - sqs:DeleteMessage
        - sqs:DeleteMessageBatch
        - sqs:GetQueueUrl
        - sqs:ChangeMessageVisibility
        - sqs:ChangeMessageVisibilityBatch
      Resource: "*"
    - Effect: Allow
      Action: "sns:*"
      Resource: "*"
    - Effect: Allow
      Action: "ses:*"
      Resource: "*"
    - Effect: Allow
      Action: kms:Decrypt
      Resource: "*"

custom:
  tableDiscovery: discovery-${opt:stage, env:STAGE, "dev"}
  tableHarvest: harvest-${opt:stage, env:STAGE, "dev"}
  tableStrategyMeta: strategyMeta-${opt:stage, env:STAGE, "dev"}
  tableStrategyDetails: strategyDetails-${opt:stage, env:STAGE, "dev"}
  queueHarvest: harvest-${opt:stage, env:STAGE, "dev"}
  queueStrategy: strategy-${opt:stage, env:STAGE, "dev"}
  sesSender: crypto.mastheader@gmail.com
  sesRecipient: crypto.mastheader@gmail.com
  snsTopicDiscovery: discovery-${opt:stage, env:STAGE, "dev"}
  snsTopicStrategy: strategy-${opt:stage, env:STAGE, "dev"}
  snsTopicHarvest: harvest-${opt:stage, env:STAGE, "dev"}
  timeoutHarvest: 300
  timeoutStrategy: 120
  strategyDAAEnter: 0.1
  strategyDAAExit: -0.4
  strategySMALookback: 7
  strategyVolatilityEnter: 0.7
  strategyVolatilityExit: 1.4
  logRetentionInDays: 7
  capacities:
    - table: TableHarvest
      read:
        minimum: 1
        maximum: 500
        usage: 0.75
      write:
        minimum: 1
        maximum: 10000
        usage: 0.75
    - table: TableStrategyDetails
      read:
        minimum: 1
        maximum: 100
        usage: 0.75
      write:
        minimum: 1
        maximum: 10000
        usage: 0.75
    - table: TableStrategyMeta
      read:
        minimum: 1
        maximum: 100
        usage: 0.75
      write:
        minimum: 1
        maximum: 10000
        usage: 0.75
plugins:
  - serverless-python-requirements
  - serverless-plugin-log-retention
  - serverless-dynamodb-autoscaling

functions:
  discovery:
    handler: cmd/discovery/handler.discovery
    timeout: ${self:custom.timeoutHarvest}
    events:
      - schedule: cron(0 0 ? * SUN *) # Sundays at 00:00 UTC
  discoveryNotify:
    handler: cmd/discovery/handler.notify
    events:
      - sns: ${self:custom.snsTopicDiscovery}
  harvestPrimer:
    handler: cmd/harvest/primer.primer
    events:
      - schedule: cron(1 * ? * * *) # 01:00 UTC  (Midnight + 1 min) every day
  harvestExecutor:
    handler: cmd/harvest/executor.executor
    timeout: ${self:custom.timeoutHarvest}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - QueueHarvest
              - Arn
          batchSize: 1
  strategy:
    handler: cmd/strategy/strategy.strategy
    timeout: ${self:custom.timeoutStrategy}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - QueueStrategy
              - Arn
          batchSize: 1
resources:
  Resources:
    TableDiscovery:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableDiscovery}
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TableHarvest:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableHarvest}
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
          - AttributeName: datetime_metric
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
          - AttributeName: datetime_metric
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TableStrategyMeta:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableStrategyMeta}
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TableStrategyDetails:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableStrategyDetails}
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
          - AttributeName: guid_details
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
          - AttributeName: guid_details
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    QueueHarvest:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueHarvest}
        VisibilityTimeout: 300
    QueueStrategy:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueStrategy}
        VisibilityTimeout: 240
